# Generated by Django 4.1.4 on 2022-12-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='session_year',
        ),
        migrations.AddField(
            model_name='alumni',
            name='org_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='alumni',
            name='passing_year',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='address',
            field=models.TextField(default=None),
        ),
    ]
