# Generated by Django 4.1.4 on 2022-12-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_alumni_session_year_alumni_org_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='org_name',
        ),
    ]
