# Generated by Django 4.1.4 on 2022-12-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_alumni_org_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='passing_year',
        ),
    ]
