# Generated by Django 4.1.4 on 2022-12-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_staff_notification_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_Notification',
            new_name='StaffNotification',
        ),
    ]
