# Generated by Django 4.1.4 on 2022-12-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_staff_notification_staffnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='passing_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
