# Generated by Django 4.1.4 on 2022-12-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alumni_passing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
