# Generated by Django 4.1.4 on 2022-12-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_staffnotification_staff_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('alum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumni')),
            ],
        ),
    ]
