# Generated by Django 4.1.4 on 2022-12-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_applyformembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyformembership',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
