# Generated by Django 4.1.4 on 2023-01-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alumnifeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnifeedback',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alumnifeedback',
            name='feedback_reply',
            field=models.TextField(null=True),
        ),
    ]
